version: '2'

services:
  dask_scheduler:
    image: 'daskdev/dask:2021.6.2'
    command: dask-scheduler
    ports:
      - '8786:8786'
      - '8787:8787'

  dask_worker:
    image: 'daskdev/dask:2021.6.2'
    command: dask-worker dask_scheduler:8786
    volumes:
      - ./data:/data